//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace Persistence.AppWS.WS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SI_OS_CustomerStatementBinding", Namespace = "http://cemex.com/SINCO/ECCMEX/CustomerStatement")]
    public partial class BS_SINCO_PRD_GBL_SI_OS_CustomerStatement_x_x : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback requestCustomerStatementOperationCompleted;

        /// <remarks/>
        public BS_SINCO_PRD_GBL_SI_OS_CustomerStatement_x_x(String url)
        {
            //this.Url = @"http://mxoccsapeip01.noam.cemexnet.com:8180/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_SINCO_PRD_GBL&receiverParty=&receiverService=&interface=SI_OS_CustomerStatement&interfaceNamespace=http%3A%2F%2Fcemex.com%2FSINCO%2FECCMEX%2FCustomerStatement";
            this.Url = url;
        }
        /// <remarks/>
        public event requestCustomerStatementCompletedEventHandler requestCustomerStatementCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_CustomerStatementResp", Namespace = "http://cemex.com/SINCO/ECCMEX/CustomerStatement")]
        public DT_CustomerStatementResp requestCustomerStatement([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://cemex.com/SINCO/ECCMEX/CustomerStatement")] DT_CustomerStatementReq MT_CustomerStatementReq)
        {
            object[] results = this.Invoke("requestCustomerStatement", new object[] {
                    MT_CustomerStatementReq});
            return ((DT_CustomerStatementResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginrequestCustomerStatement(DT_CustomerStatementReq MT_CustomerStatementReq, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("requestCustomerStatement", new object[] {
                    MT_CustomerStatementReq}, callback, asyncState);
        }

        /// <remarks/>
        public DT_CustomerStatementResp EndrequestCustomerStatement(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DT_CustomerStatementResp)(results[0]));
        }

        /// <remarks/>
        public void requestCustomerStatementAsync(DT_CustomerStatementReq MT_CustomerStatementReq)
        {
            this.requestCustomerStatementAsync(MT_CustomerStatementReq, null);
        }

        /// <remarks/>
        public void requestCustomerStatementAsync(DT_CustomerStatementReq MT_CustomerStatementReq, object userState)
        {
            if ((this.requestCustomerStatementOperationCompleted == null))
            {
                this.requestCustomerStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestCustomerStatementOperationCompleted);
            }
            this.InvokeAsync("requestCustomerStatement", new object[] {
                    MT_CustomerStatementReq}, this.requestCustomerStatementOperationCompleted, userState);
        }

        private void OnrequestCustomerStatementOperationCompleted(object arg)
        {
            if ((this.requestCustomerStatementCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestCustomerStatementCompleted(this, new requestCustomerStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cemex.com/SINCO/ECCMEX/CustomerStatement")]
    public partial class DT_CustomerStatementReq
    {

        private string i_KUNNRField;

        private string i_VKORGField;

        private string i_VTWEGField;

        private string i_SPARTField;

        private string i_FCURRField;

        private string i_TCURRField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_KUNNR
        {
            get
            {
                return this.i_KUNNRField;
            }
            set
            {
                this.i_KUNNRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_VKORG
        {
            get
            {
                return this.i_VKORGField;
            }
            set
            {
                this.i_VKORGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_VTWEG
        {
            get
            {
                return this.i_VTWEGField;
            }
            set
            {
                this.i_VTWEGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_SPART
        {
            get
            {
                return this.i_SPARTField;
            }
            set
            {
                this.i_SPARTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_FCURR
        {
            get
            {
                return this.i_FCURRField;
            }
            set
            {
                this.i_FCURRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_TCURR
        {
            get
            {
                return this.i_TCURRField;
            }
            set
            {
                this.i_TCURRField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cemex.com/SINCO/ECCMEX/CustomerStatement")]
    public partial class DT_CustomerStatementResp
    {

        private string e_CNAMEField;

        private string e_AUFSOField;

        private string e_TAUSOField;

        private string e_BITOCField;

        private string e_BITONField;

        private string e_AUFSDField;

        private string e_TAUSDField;

        private string e_ZTERMField;

        private string e_NTERMField;

        private string e_CARTTField;

        private string e_SLDAFField;

        private string e_CARNTField;

        private string e_LCCURField;

        private string e_LIMCRField;

        private string e_LICURField;

        private string e_UKURSField;

        private string e_IPFACField;

        private string e_EXCEPTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_CNAME
        {
            get
            {
                return this.e_CNAMEField;
            }
            set
            {
                this.e_CNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_AUFSO
        {
            get
            {
                return this.e_AUFSOField;
            }
            set
            {
                this.e_AUFSOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_TAUSO
        {
            get
            {
                return this.e_TAUSOField;
            }
            set
            {
                this.e_TAUSOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_BITOC
        {
            get
            {
                return this.e_BITOCField;
            }
            set
            {
                this.e_BITOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_BITON
        {
            get
            {
                return this.e_BITONField;
            }
            set
            {
                this.e_BITONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_AUFSD
        {
            get
            {
                return this.e_AUFSDField;
            }
            set
            {
                this.e_AUFSDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_TAUSD
        {
            get
            {
                return this.e_TAUSDField;
            }
            set
            {
                this.e_TAUSDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_ZTERM
        {
            get
            {
                return this.e_ZTERMField;
            }
            set
            {
                this.e_ZTERMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_NTERM
        {
            get
            {
                return this.e_NTERMField;
            }
            set
            {
                this.e_NTERMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_CARTT
        {
            get
            {
                return this.e_CARTTField;
            }
            set
            {
                this.e_CARTTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_SLDAF
        {
            get
            {
                return this.e_SLDAFField;
            }
            set
            {
                this.e_SLDAFField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_CARNT
        {
            get
            {
                return this.e_CARNTField;
            }
            set
            {
                this.e_CARNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_LCCUR
        {
            get
            {
                return this.e_LCCURField;
            }
            set
            {
                this.e_LCCURField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_LIMCR
        {
            get
            {
                return this.e_LIMCRField;
            }
            set
            {
                this.e_LIMCRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_LICUR
        {
            get
            {
                return this.e_LICURField;
            }
            set
            {
                this.e_LICURField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_UKURS
        {
            get
            {
                return this.e_UKURSField;
            }
            set
            {
                this.e_UKURSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_IPFAC
        {
            get
            {
                return this.e_IPFACField;
            }
            set
            {
                this.e_IPFACField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_EXCEPTION
        {
            get
            {
                return this.e_EXCEPTIONField;
            }
            set
            {
                this.e_EXCEPTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void requestCustomerStatementCompletedEventHandler(object sender, requestCustomerStatementCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestCustomerStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal requestCustomerStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DT_CustomerStatementResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DT_CustomerStatementResp)(this.results[0]));
            }
        }
    }
}