//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Client.Web.WSDL_CC_MRP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cemex.com/SINCO/ECCMEX/CustomerStatement", ConfigurationName="WSDL_CC_MRP.SI_OS_CustomerStatement")]
    public interface SI_OS_CustomerStatement {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación requestCustomerStatement no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication.Client.Web.WSDL_CC_MRP.requestCustomerStatementResponse requestCustomerStatement(WebApplication.Client.Web.WSDL_CC_MRP.requestCustomerStatementRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cemex.com/SINCO/ECCMEX/CustomerStatement")]
    public partial class DT_CustomerStatementReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_KUNNRField;
        
        private string i_VKORGField;
        
        private string i_VTWEGField;
        
        private string i_SPARTField;
        
        private string i_FCURRField;
        
        private string i_TCURRField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_KUNNR {
            get {
                return this.i_KUNNRField;
            }
            set {
                this.i_KUNNRField = value;
                this.RaisePropertyChanged("I_KUNNR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_VKORG {
            get {
                return this.i_VKORGField;
            }
            set {
                this.i_VKORGField = value;
                this.RaisePropertyChanged("I_VKORG");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_VTWEG {
            get {
                return this.i_VTWEGField;
            }
            set {
                this.i_VTWEGField = value;
                this.RaisePropertyChanged("I_VTWEG");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_SPART {
            get {
                return this.i_SPARTField;
            }
            set {
                this.i_SPARTField = value;
                this.RaisePropertyChanged("I_SPART");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_FCURR {
            get {
                return this.i_FCURRField;
            }
            set {
                this.i_FCURRField = value;
                this.RaisePropertyChanged("I_FCURR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_TCURR {
            get {
                return this.i_TCURRField;
            }
            set {
                this.i_TCURRField = value;
                this.RaisePropertyChanged("I_TCURR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cemex.com/SINCO/ECCMEX/CustomerStatement")]
    public partial class DT_CustomerStatementResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_CNAMEField;
        
        private string e_AUFSOField;
        
        private string e_TAUSOField;
        
        private string e_BITOCField;
        
        private string e_BITONField;
        
        private string e_AUFSDField;
        
        private string e_TAUSDField;
        
        private string e_ZTERMField;
        
        private string e_NTERMField;
        
        private string e_CARTTField;
        
        private string e_SLDAFField;
        
        private string e_CARNTField;
        
        private string e_LCCURField;
        
        private string e_LIMCRField;
        
        private string e_LICURField;
        
        private string e_UKURSField;
        
        private string e_IPFACField;
        
        private string e_EXCEPTIONField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_CNAME {
            get {
                return this.e_CNAMEField;
            }
            set {
                this.e_CNAMEField = value;
                this.RaisePropertyChanged("E_CNAME");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string E_AUFSO {
            get {
                return this.e_AUFSOField;
            }
            set {
                this.e_AUFSOField = value;
                this.RaisePropertyChanged("E_AUFSO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string E_TAUSO {
            get {
                return this.e_TAUSOField;
            }
            set {
                this.e_TAUSOField = value;
                this.RaisePropertyChanged("E_TAUSO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string E_BITOC {
            get {
                return this.e_BITOCField;
            }
            set {
                this.e_BITOCField = value;
                this.RaisePropertyChanged("E_BITOC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string E_BITON {
            get {
                return this.e_BITONField;
            }
            set {
                this.e_BITONField = value;
                this.RaisePropertyChanged("E_BITON");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string E_AUFSD {
            get {
                return this.e_AUFSDField;
            }
            set {
                this.e_AUFSDField = value;
                this.RaisePropertyChanged("E_AUFSD");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string E_TAUSD {
            get {
                return this.e_TAUSDField;
            }
            set {
                this.e_TAUSDField = value;
                this.RaisePropertyChanged("E_TAUSD");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string E_ZTERM {
            get {
                return this.e_ZTERMField;
            }
            set {
                this.e_ZTERMField = value;
                this.RaisePropertyChanged("E_ZTERM");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string E_NTERM {
            get {
                return this.e_NTERMField;
            }
            set {
                this.e_NTERMField = value;
                this.RaisePropertyChanged("E_NTERM");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string E_CARTT {
            get {
                return this.e_CARTTField;
            }
            set {
                this.e_CARTTField = value;
                this.RaisePropertyChanged("E_CARTT");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string E_SLDAF {
            get {
                return this.e_SLDAFField;
            }
            set {
                this.e_SLDAFField = value;
                this.RaisePropertyChanged("E_SLDAF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string E_CARNT {
            get {
                return this.e_CARNTField;
            }
            set {
                this.e_CARNTField = value;
                this.RaisePropertyChanged("E_CARNT");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string E_LCCUR {
            get {
                return this.e_LCCURField;
            }
            set {
                this.e_LCCURField = value;
                this.RaisePropertyChanged("E_LCCUR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string E_LIMCR {
            get {
                return this.e_LIMCRField;
            }
            set {
                this.e_LIMCRField = value;
                this.RaisePropertyChanged("E_LIMCR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string E_LICUR {
            get {
                return this.e_LICURField;
            }
            set {
                this.e_LICURField = value;
                this.RaisePropertyChanged("E_LICUR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string E_UKURS {
            get {
                return this.e_UKURSField;
            }
            set {
                this.e_UKURSField = value;
                this.RaisePropertyChanged("E_UKURS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string E_IPFAC {
            get {
                return this.e_IPFACField;
            }
            set {
                this.e_IPFACField = value;
                this.RaisePropertyChanged("E_IPFAC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string E_EXCEPTION {
            get {
                return this.e_EXCEPTIONField;
            }
            set {
                this.e_EXCEPTIONField = value;
                this.RaisePropertyChanged("E_EXCEPTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestCustomerStatementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cemex.com/SINCO/ECCMEX/CustomerStatement", Order=0)]
        public WebApplication.Client.Web.WSDL_CC_MRP.DT_CustomerStatementReq MT_CustomerStatementReq;
        
        public requestCustomerStatementRequest() {
        }
        
        public requestCustomerStatementRequest(WebApplication.Client.Web.WSDL_CC_MRP.DT_CustomerStatementReq MT_CustomerStatementReq) {
            this.MT_CustomerStatementReq = MT_CustomerStatementReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestCustomerStatementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cemex.com/SINCO/ECCMEX/CustomerStatement", Order=0)]
        public WebApplication.Client.Web.WSDL_CC_MRP.DT_CustomerStatementResp MT_CustomerStatementResp;
        
        public requestCustomerStatementResponse() {
        }
        
        public requestCustomerStatementResponse(WebApplication.Client.Web.WSDL_CC_MRP.DT_CustomerStatementResp MT_CustomerStatementResp) {
            this.MT_CustomerStatementResp = MT_CustomerStatementResp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OS_CustomerStatementChannel : WebApplication.Client.Web.WSDL_CC_MRP.SI_OS_CustomerStatement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OS_CustomerStatementClient : System.ServiceModel.ClientBase<WebApplication.Client.Web.WSDL_CC_MRP.SI_OS_CustomerStatement>, WebApplication.Client.Web.WSDL_CC_MRP.SI_OS_CustomerStatement {
        
        public SI_OS_CustomerStatementClient() {
        }
        
        public SI_OS_CustomerStatementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OS_CustomerStatementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_CustomerStatementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_CustomerStatementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.Client.Web.WSDL_CC_MRP.requestCustomerStatementResponse WebApplication.Client.Web.WSDL_CC_MRP.SI_OS_CustomerStatement.requestCustomerStatement(WebApplication.Client.Web.WSDL_CC_MRP.requestCustomerStatementRequest request) {
            return base.Channel.requestCustomerStatement(request);
        }
        
        public WebApplication.Client.Web.WSDL_CC_MRP.DT_CustomerStatementResp requestCustomerStatement(WebApplication.Client.Web.WSDL_CC_MRP.DT_CustomerStatementReq MT_CustomerStatementReq) {
            WebApplication.Client.Web.WSDL_CC_MRP.requestCustomerStatementRequest inValue = new WebApplication.Client.Web.WSDL_CC_MRP.requestCustomerStatementRequest();
            inValue.MT_CustomerStatementReq = MT_CustomerStatementReq;
            WebApplication.Client.Web.WSDL_CC_MRP.requestCustomerStatementResponse retVal = ((WebApplication.Client.Web.WSDL_CC_MRP.SI_OS_CustomerStatement)(this)).requestCustomerStatement(inValue);
            return retVal.MT_CustomerStatementResp;
        }
    }
}
